name: ci

on:
  pull_request:
  push:
    branches: [ master ]

env:
  POSTGRES_DB_NAME: "dbname"
  POSTGRES_DB_USER: "rootuser"
  POSTGRES_DB_PASS: "changeme"
  APP_PORT: "8080"
  APP_SECRET_KEY: "changeme"
  APP_ALLOWED_HOSTS: "*"
  APP_DEBUG: "1"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: pre-commit/action@v3.0.0
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Test and Generate Coverage Report
        run: docker-compose run --rm app sh -c "coverage run --source='.' manage.py test && coverage report && coverage xml"
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./src/app/
          fail_ci_if_error: true
          verbose: true
    needs: [ pre-commit ]
