name: tests

on:
  pull_request:
  push:
    branches: [ master ]

env:
  POSTGRES_DB_NAME: "dbname"
  POSTGRES_DB_USER: "rootuser"
  POSTGRES_DB_PASS: "changeme"
  APP_PORT: "8080"
  APP_SECRET_KEY: "changeme"
  APP_ALLOWED_HOSTS: "*"
  APP_DEBUG: "1"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
